### ISSUE TITLE
Windows : On Pairing get - WARNING:bumble.smp:pairing failure (SMP_INVALID_PARAMETERS_ERROR)

### ISSUE THREAD

**Issue by pymenow** [google/bumble#182]
Bumble : v0.0.148
Windows : 11  **22621.1635**

The events leading to the failure:

A connection is established with another device (remote device address: 34:2E:B7:DF:76:26), and the connection handle is 0x0048.
The Secure Simple Pairing (SSP) process takes place, which involves exchanging pairing random values and checking Diffie-Hellman keys.
The encryption is enabled for the connection.
The Identity Resolving Key (IRK) and Identity Address are exchanged.
**A GATT request for writing an attribute value is performed**, followed by another request to read primary services.
An SMP pairing failure occurs due to invalid parameters (SMP_INVALID_PARAMETERS_ERROR), resulting in a warning message.
The connection is terminated by the remote user (HCI_REMOTE_USER_TERMINATED_CONNECTION_ERROR), and the device starts advertising again.

```
DEBUG:bumble.smp:>>> Sending SMP Command on connection [0x0048] 34:2E:B7:DF:76:26/P: SMP_IDENTITY_ADDRESS_INFORMATION_COMMAND:
  addr_type: RANDOM_DEVICE_ADDRESS
  bd_addr:   6F:6D:6E:79:6B:01
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=6) ACL: handle=0x0048pb=0, bc=0, data_total_length=12, data=080006000901016b796e6d6f
DEBUG:bumble.transport.usb:submit ACL
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0048pb=2, bc=0, data_total_length=9, data=050004001209000200
DEBUG:bumble.hci:<<< ACL PDU: 050004001209000200
DEBUG:bumble.gatt_server:GATT Request to server: [0x0048] ATT_WRITE_REQUEST:
  attribute_handle: 0x0009
  attribute_value:  0200
DEBUG:bumble.gatt_server:GATT Response from server: [0x0048] ATT_WRITE_RESPONSE
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0048pb=0, bc=0, data_total_length=5, data=0100040013
DEBUG:bumble.transport.usb:submit ACL
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     72
  num_completed_pack
ets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0048pb=2, bc=0, data_total_length=6, data=02000600050a
DEBUG:bumble.hci:<<< ACL PDU: 02000600050a
DEBUG:bumble.smp:<<< Received SMP Command on connection [0x0048] 34:2E:B7:DF:76:26/P: SMP_PAIRING_FAILED_COMMAND:
  reason: SMP_INVALID_PARAMETERS_ERROR
WARNING:bumble.smp:pairing failure (SMP_INVALID_PARAMETERS_ERROR)
```

Full logs added below 
[SMP_PAIR_FAIL.txt](https://github.com/google/bumble/files/11360453/SMP_PAIR_FAIL.txt)

**Comment by barbibulle** [comment]
Thanks for the detailed report.
First, I don't think that the GATT exchange here is related to the issue. GATT and SMP are independent protocols. One stack may have some requirements for what level of security it wants in order to do its GATT operations, but GATT operations should not themselves make pairing fail.
What's shown here w/r/t the pairing protocol is that it all goes well until it's time for the peripheral to distribute pairing elements. Early on in the protocol, we can see that based on the parameters exchanged in the pairing request/response, the required distribution is just the identity (`expecting distributions: ['SMP_Identity_Information_Command', 'SMP_Identity_Address_Information_Command']`).
Distribution happens once the link is encrypted, which we see happens here (`Connection Encryption Change`). The peripheral sends its identity and identity address (`SMP_IDENTITY_INFORMATION_COMMAND` and `SMP_IDENTITY_ADDRESS_INFORMATION_COMMAND`), as per the spec ("... IdKey is a 1-bit field that is set to one to indicate that the device shall distribute IRK using the Identity Information command followed by its public device or static random address using Identity Address Information.") 
What happens next is that the central fails the pairing with `SMP_INVALID_PARAMETERS_ERROR` and then disconnects. It's not clear why the central doesn't like the `SMP_IDENTITY_ADDRESS_INFORMATION_COMMAND` sent by the peripheral, since that's what the spec says should happen (and that works on Android, iOS and macOS). I haven't tried Windows much, but I will give it a shot to see if I can replicate this scenario. Maybe @uael has an idea what may be going here?

**Comment by barbibulle** [comment]
Followup: I just tried on a basic Windows 10 laptop, with the "Bluetooth LE Explorer" app. On a mac, I ran `python apps/pair.py device1.json usb:0` (where `device1.json` is the file from the `examples/` dir). On Windows, I saw the "Bumble" device show up, and was able to pair (using the "Pair" button on the device tile). It prompted me to compare the PIN code on Windows and on the mac (on the mac, the prompt comes from the Bumble pair app, not the OS, of course). Pairing succeeded.

**Comment by pymenow** [comment]
Hello, Thanks for the updates.

The original issue in this case, didnt have anything to do with pair.py app. 
However I decided to try the pair.py + Bluetooth LE Explorer app.

I am running pair.py on Windows 11 : 22H2 (22621.1635), with default device1.json.
On the same Windows setup - > Ran Bluetooth LE Explorer app - I was able to connect with the pin and pairing succeded .

I relaised I had changed the irk to "irk": "47688648938700803069208893744406629894" and MAC address for the application I was building , instead of using the default irk and MAC address that came with the device1.json . 

I reverted my custom json with the default irk and MAC address and pairing worked fine. 

The MAC address I used : "6F:6D:6E:79:6B:01" I reverted only this in my json and pairing worked fine there after.
Reverted the irk to the custom one and it continued to work fine.
I dont understand why the custom MAC address has an issue ! 

Looking at the default MAC address that comes in device1.json F0:F1:F2:F3:F4:F5 , just changing this to 1F:F2:F3:F4:F5:F6 causes the issue to reproduce.

**Comment by pymenow** [comment]
Now coming back to the original use case for which I filed the issue.
In my custom app running on Windows 11 : 22H2 (22621.1635), I would see the SMP_INVALID_PARAMETERS_ERROR by searching for the device using default windows in built bluetooth & devices > devices screen -> Add Device and select on the device to pair.
After I reverted the MAC address on my custom json file , even this pairing worked absolutely fine.
Looks like some restrictions on the MAC address  , specifically if the first character is a digit , instead of an alphabet . 
What worked - "F6:6D:6E:79:6B:01"
What didnt work - "6F:6D:6E:79:6B:01"

**Comment by uael** [comment]
@pymenow That was my first guess when I saw the random address `6F:6D:6E:79:6B:01` which does not look that random.

Addresses have two types, public and random. BR/EDR controller have a unique predefined public address. Low energy use multiple generated random addresses of different types.

4 device address types are defined (see [Vol 2] Part B, Section 1.3) with the following format:
```
- public:         | OUI  (24 bit) | Vendor (24 bit)    | cf IEEE 802-2014
- static:         | Random part (46 bit)           |1|1|
- non resolvable: | Random part (46 bit)           |0|0|
- resolvable:     | hash (24 bit) | prand (22 bit) |1|0|
```

OUI: organizationally unique identifier

That's why the address `F6:6D:6E:79:6B:01` worked and not `6F:6D:6E:79:6B:01`:
```
0xF6 -> 0b11110110 -> 0b11000000 -> static
0x6F -> 0b01101111 -> 0b01000000 -> resolvable
```

In your case, since your not using either a public or an identity address, the address must be of type `static`

**Comment by pymenow** [comment]
Thanks so we would have to stick to static addresses. That clears it .
