### ISSUE TITLE
Custom BT stack with Link Relay

### ISSUE THREAD

**Issue by akuker** [google/bumble#191]
Not sure this is really an issue, but I'm looking to do a modified version of [Use Case 6](https://google.github.io/bumble/use_cases/use_case_5.html). I have a custom Bluetooth stack, which uses a standard H4 HCI interface. I'm planning to use the Linux hci_vhci.ko module, but don't have to.

I want to connect this BT stack to a link relay, which will have several virtual devices connected.

I haven't able to find an example/application in the bumble repository that does what I'm trying to do. It looks like I need to create something like `run_simulator.py` which will create a RemoteLink to the link_relay, then connect that to a virtual controller, which uses `vhci` as its host sink/source. (also, without the devices, since those are all connected to the link relay)

```
                                     ┌───────────────┐
                                     │   Custom BT   │
                                     │     Stack     │
                                     ├───────────────┤
                                     │ HCI Interface │
                                     └───────────────┘
                                             ▲
                                             │
                                             │hci_vhci.ko
                                             │
                                             ▼ Custom python app (pseudocode follows)
                          ┌───────────────────────────────────────────┐
                          │rlink = RemoteLink(ws:127.0.0.1:10723)     │
                          │open_transport_or_link(vhci) as (vhci_host)│
                          │ctrl = Controller (vhci_host, rlink)       │
                          │wait_for_termination()                     │
                          └───────────────────────────────────────────┘
                                             ▲
                                             │
+--------++--------++------------+           │websock     +------------++--------++--------+
| Bumble || Bumble || Bumble     |           │            | Bumble     || Bumble || Bumble |
| Python || Host   || Controller |<--+       ▼        +-->| Controller || Host   || Python |
| App    ||        ||            |   |   +--------+   |   |            ||        || App    |
+--------++--------++------------+   +-->| Bumble |<--+   +------------++--------++--------+
                                         | Link   |
+--------++--------++------------+   +-->| Relay  |<--+   +------------++--------++--------+
| Bumble || Bumble || Bumble     |   |   +--------+   |   | Bumble     || Bumble || Bumble |
| Python || Host   || Controller |<--+                +-->| Controller || Host   || Python |
| App    ||        ||            |                        |            ||        || App    |
+--------++--------++------------+                        +------------++--------++--------+
```

Am I on the right track? Or is there a better / more straightforward way to do this?

Thank you for your help!!

**Comment by barbibulle** [comment]
You're definitely on the right track, this should be possible.
I'll preface the following text with a caveat: the link relay (and the Bumble Controller class that uses it) isn't full-featured, and is a fairly low-fidelity, partial, simulator for a virtual link between virtual controllers. We'll probably end up either deprecating it at some point, and/or replace it with something more comprehensive, like the "root canal" component that's now part of the Android AOSP project, used within the "netsim" daemon also part of AOSP, see https://android.googlesource.com/platform/tools/netsim/+/refs/heads/master. If/when we find a good way to package it as a standalone component so that it can be used with Bumble without having to pull the entire AOSP set of repos, that may become a viable option). But for now, the Bumble Controller and virtual link component is probably good enough for a number of use cases, including local unit tests.

Now, as to the specific scenario you're looking at here: (i'm not sure what script you're referring to by `run_simulator.py`, but that doesn't matter), what you want is to instantiate a bumble.Controller object, connected to the relay. That controller exposes an HCI source and sink on its "host" side, and you want to connect that to your stack. If your stack is exposed via /dev/vhci, that's a viable option, but any other supported transport from the bumble/transport collection would work as well (TCP, UDP, WS, PTY, ...). Unfortunately, the `run_controller.py` example isn't a good example for that, because that example instantiates a virtual controller, but doesn't expose it to an external stack, it exposes it to a local stack. 
But... you should be able to do this with a combination of the existing apps included in the project.
1/ Run the link relay, ready to accept client connections. `bumble-link-relay` (or `python apps/link_relay/link_relay.py` if from source). This will listen on port 10723 by default.
2/ Run an HCI bridge from your custom stack to the link relay, via a local controller (the HCI bridge app does use the `open_transport_or_link` function, so it can automatically instantiate a controller when the destination is the relay and not directly an HCI transport). The "host" side of the bridge can be whatever transport you want, but I suppose `vhci` would be appropriate for you here. Something like: `bumble-hci-bridge vhci link-relay:ws://localhost:10723/test` (or `python apps/hci_bridge.py xxxx` if from source).
3/ Any other virtual device that connects to the `/test` (using `/test` here to match the "room" name used in step 2, but any other name would be fine, as long as they match) "room" of the relay will then be able to communicate with the stack that's bridged in step 2. For example, `bumble-scan link-relay:ws://localhost:10723/test`

**Comment by barbibulle** [comment]
Just one more thing: when running apps like `bumble-hci-bridge`, it may be helpful to set  the env var `BUMBLE_LOGLEVEL=debug` to see a detailed log of the HCI traffic. The same applies to all other tools, which don't have verbose logs enabled by default. Alternatively, if you want to record the HCI packets to a file instead of debug logs, you can set `BUMBLE_SNOOPER=file:my_snoop_file.log` (see `bumble/snoop.py` for details on the snooper syntax).

**Comment by akuker** [comment]
Thank you very much @barbibulle for the thorough response! 

> I'll preface the following text with a caveat: the link relay (and the Bumble Controller class that uses it) isn't full-featured, and is a fairly low-fidelity, partial, simulator for a virtual link between virtual controllers. We'll probably end up either deprecating it at some point, and/or replace it with something more comprehensive, like the "root canal" component that's now part of the Android AOSP project, used within the "netsim" daemon also part of AOSP,

Are there any high-level descriptions of how netsim/rootcanal work together? It looks like the netsim documentation is pretty limited currently, and I haven't come across a good description of the root canal design. It looks straight-forward to use with an Android emulator, but outside of that use case, I haven't really found any good information.

I'm going to be developing a bunch of "devices" over the coming months, and I'd like to align with the direction the overall bumble project is going. 

Thanks again!!!

**Comment by uael** [comment]
Rootcanal is a standalone executable, it listen for TCP connections (used for HCI traffic) where for each TCP connections a virtual controller is instantiate. 

It should be moved from AOSP to github in the next weeks🤞 (please correct me if I'm wrong @hchataing)

**Comment by hchataing** [comment]
Netsim integrates rootcanal as a library. You can configure it to open a tcp server of grpc server to access the bluetooth controller. Work to make it open source on github has been delayed slightly because of internal dependencies on AOSP tooling, but I am hoping to make it available soon :)

**Comment by akuker** [comment]
Thank you all for the great information!! Netsim looks like its intended to support more than just BT, so that will be handy. 

I look forward to hearing how rootcanal/netsim progress and hopefully switching over to them soon!

Is the project still open to pull requests/enhancements to the existing controller & link relay? I found a few HCI commands that I need to add to support my use case.

I was able to get basic communication working, so I'll mark this ticket as closed, but I welcome any additional info you're willing to share!

**Comment by hchataing** [comment]
> Is the project still open to pull requests/enhancements to the existing controller & link relay? 
> I found a few HCI commands that I need to add to support my use case.

Please go ahead and forward your requirements. You can submit patches to AOSP but I would understand if the setup is too complicated for you. It will be easier to receive external contributions when it is opensources :)

**Comment by akuker** [comment]
For now, I'm focusing on the Bumble/python functionality, so I'll be submitting the patches to github. The additional updates are pretty small (for example: https://github.com/google/bumble/compare/main...akuker:bumble:akuker-fork/main) 

(Disclaimer - that patch isn't merge-worthy yet. It was just a quick hack for the moment. I still need to think through some of the values its returning)
