### ISSUE TITLE
Design question on sink classes and emits

### ISSUE THREAD

**Issue by paulhamsh** [google/bumble#252]
Hi
First, this is a great project - I am trying to understand BLE and seeing code in Python is cool!
I am reading through the code to see how it works from USB through to Gatt Server.
I think the HCI layer uses sink classes then above that uses pyee Emitter classes. Is that right and is there a reason to change approaches across layers?
Just trying to understand the overall design.
Thanks

**Comment by zxzxwu** [comment]
Do you mean `device<->host` uses Pyee but `host<->transport` uses sink method, and the inconsistency is somehow weird?

**Comment by barbibulle** [comment]
The reason there are different ways layers call each other is because initially the code base didn't use pyee, that came later. Not everything has been updated to use pyee, so there are still direct calls to `on_xxx` methods, or sink functions (very lightweight for cases where the emitter holds directly a reference to a function, rather than an object on which it calls one or more methods by name).
For the transport library, it will likely remain this way, as the source/sink model is close to the way asyncio works in general with transports and protocols (ex: `data_receveived` methods being called), and is quite a bit lighter than the generic multi-listener model of pyee. For other layers, like gatt, it is possible that we'll end up updating to pyee events at some point.

**Comment by paulhamsh** [comment]
Ah - thank you for explaining. That really helps
