### ISSUE TITLE
HCI_Reset is missing status

### ISSUE THREAD

**Issue by AlanRosenthal** [google/bumble#410]
https://github.com/google/bumble/blob/main/bumble/hci.py#L2914-L2919

HCI_Reset returns status

**Comment by barbibulle** [comment]
While it's true that HCI_Reset response doesn't have a field explicitly named `status`, it is typically not needed. 
Thats because in order to avoid a large number of boilerplate 'status' definition (which exist in many HCI command responses), the model knows that for "simple" HCI commands that have just a status in the return parameters, the first byte is the status.
User code typically doesn't look at this status code directly, since it is already handled in the `host.send_command`, where the `check_result` boolean tells the function whether to extract and check the status. When `check_result` is true and the HCI command return parameters doesn't explicitly have a `status` field, the code extracts the status from the first byte.

Now, if we see some value in accessing `return_parameters.status` instead of ` response.return_parameters[0]`, we could introduce a flavor of the `HCI_Command.command` decorator, which would name the return_parameters.status field explicitly (we could call that decorator `HCI_Command.simple_command` for example. 

This is how the status field is read in `host.py,  Host.send_command()`:
```
elif isinstance(response.return_parameters, bytes):
                        # return parameters first field is a one byte status code
                        status = response.return_parameters[0]
```
