### ISSUE TITLE
Support for Cuttlefish Android Virtual device

### ISSUE THREAD

**Issue by jaisontj** [google/bumble#413]
I am trying to work through the example here: https://google.github.io/bumble/platforms/android.html to give a cuttlefish Android Virtual device access to my ubuntu hosts bluetooth radio

The work involved seems to be figuring out a way to bridge my local hosts BT controller and the android virtual devices host BT stack.

On the host side:

The board I am using comes with BT (I did not have to attach an additional USB BT dongle). I was able to verify the USB transport with

```
python3 examples/run_classic_discovery.py $USB

### This printed out classic BT devices that were previously visible from the BT app on ubuntu
```

On the Android Virtual Device side:

I've launched cuttlefish following instructions here: https://source.android.com/docs/setup/create/cuttlefish-use
The default launch seems to be launching netsimd as well with the following params: 

```
/home/ubuntu/cf/bin/netsimd -s {"devices":[{"name":"0.0.0.0:6520","chips":[{"kind":"BLUETOOTH","fdIn":121,"fdOut":122}]}]} --hci_port=7300 --instance_num=1
```

I found the grpc port using 

```
ubuntu@mtk-genio:~/cf$ cat $XDG_RUNTIME_DIR/netsim.ini
web.port=7681
grpc.port=39069
```

Now to bridge the two, my understanding is that I need to run the HCI bridge with the android-netsim in host mode and my physical radio

Something like this
```
python3 apps/hci_bridge.py android-netsim:localhost:39069,mode=host $USB
```
This seems to be causing crashes in the bluetooth app and also killing the netsim process (Still rootcausing the issue)

The alternative is to follow this path: https://google.github.io/bumble/platforms/android.html#connecting-a-custom-virtual-controller

However, I'm unsure on the equivalent launch config to `--packet-streamer-endpoint` for cuttlefish

I was hoping to kick start this issue in hopes to know if im on the right path and if someone has already got this working for cuttlefish and not just the android emulator?

**Comment by zxzxwu** [comment]
Usually I use `tcp-client:127.0.0.1:7300` connecting to Cuttlefish's rootcanal directly, but I am not sure what's the policy of netsim.

**Comment by barbibulle** [comment]
What you’re trying to do here (connect cuttlefish to a radio), can be done, but not via netsim. Netsim is a virtual Bluetooth controller (radio) that two (or more) virtual devices can connect to and communicate with each other through. But physical devices can’t connect to netsim. What you want here (and what’s done with the Android Studio emulator on the doc you’re pointing to), is to connect cuttlefish to your physical controller. With Studio’s emulator, the emulator connects to the controller using gRPC over a TCP socket, so we run a Bumble transport in gRPC server mode, to accept the connection, and then bridge it to some other controller (in your case that would be your Linux controller). Cuttlefish is different, it doesn’t use gRPC for this, it connects to a controller via a local file descriptors (fdIn and fdOut in the netsim parameters you list here) So we need to 1/ run an HCI bridge between a file descriptor and your Linux BT controller, 2/ tell Cuttlefish to not start its own netsim to talk to, but talk to the bridge instead. I’ll follow up here shortly with some details on how to do this (typing this from my phone now, can’t try out cuttlefish).

**Comment by jaisontj** [comment]
> Usually I use `tcp-client:127.0.0.1:7300` connecting to Cuttlefish's rootcanal directly, but I am not sure what's the policy of netsim.

@zxzxwu I did try that too

Essentially launched cuttlefish with the `netsim_bt=false` param and then tried the HCI bridge

```
python3 hci_bride tcp-client:localhost:7300 $USB
```

I didnt really see the BT devices show up in the BT android app. Did the same work for you?

Can you share your setup with me please?

**Comment by jaisontj** [comment]
@barbibulle TY for your response! That makes sense! 

Awaiting the details :) 

In the meantime, I will play around with this on my end too!

**Comment by barbibulle** [comment]
Ok, here are the details:
You need to use the `-rootcanal_instance_num=` option, and optionally `-base_instance_num=`, with `launch_cvd` to tell it to forward HCI packets to an external "instance" of rootcanal (the virtual Bluetooth controller that's part of `netsim`), which in our case isn't going to actually be rootcanal, but the bumble HCI bridge in "controller" mode, presenting the same interface as rootcanal/netsim would, therefore receiving the packets and forwarding them to/from some other HCI transport, which would be your Linux HCI in your case.

There are two options:

1/

- Start the HCI bridge as the second "instance" (instances are 1-based, so that's instance=2), with: `python apps/hci_bridge.py android-netsim:_:<some-port>,mode=controller,instance=2 <some-other-hci-transport>`
- Launch cuttlefish as the first "instance", with `launch_cvd --rootcanal_instance_num=2` 

or

2/

- Start the HCI bridge as the first "instance", with `python apps/hci_bridge.py android-netsim:_:<some-port>,mode=controller <some-other-hci-transport>`
- Launch cuttlefish as the second "instance", with `launch_cvd -base_instance_num=2 --rootcanal_instance_num=1`

(note that in this case we omitted the `instance=` part of the Bumble specifier, because the current version of Bumble doesn't yet implement the 1-based contract that cuttlefish and rootcanal use, so `instance=1` wouldn't be recognized as the "default instance". We'll fix that in a later version, but for now, simply omitting the instance number does the right thing.)

**Comment by jaisontj** [comment]
Hey @barbibulle ty for the help! the instructions you provided worked out of the box :) 

Closing issue
