### ISSUE TITLE
Dangling USB File Descriptor if Program is Not Terminated Properly

### ISSUE THREAD

**Issue by hkpeprah** [google/bumble#588]
## Summary

We are seeing dangling USB file descriptors when using the `USBTransport` if the program is not terminated properly. We believe this is because the USB resources are not disposed if `.close()` is not called on the transport when the program is terminated abnormally (say canceled by a test runner):

```
        async def close(self):
            self.source.close()
            self.sink.close()
            await self.source.terminate()
            await self.sink.terminate()
            self.device.releaseInterface(self.interface)
-->         self.device.close()
            self.context.close()

            # Wait for the thread to terminate
            await self.event_loop_done
```

## Error
```
ResourceWarning: unclosed <socket.socket fd=20, family=1, type=1, proto=0>
```

## Workaround

Currently, we have our code setup to explicitly call `transport.device.close()` our consuming classes's destructor, `__del__`. Would it be possible to put that into `USBTransport`'s destructor, so that if `.close()` is not called, the USB resource is still freed?

**Comment by barbibulle** [comment]
All transport classes, including `UsbTransport` implement an async context manager, which you should use in order to guarantee that the resources will be free'd. Using the async context manager is preferred to explicitly calling `close()`.
A typical use for a transport goes like this:
```
async with open_transport(...):
   ...
```
When the code in the `async with` block ends, the transport will be closed.
