### ISSUE TITLE
Macbook bluetooth access 

### ISSUE THREAD

**Issue by yakerm** [google/bumble#97]
Hello,
I would like to know how can I use the library with a Macbook Pro. Directly by using the mac bluetooth Chip (not a dongle). I don't know if you already have implemented this feature. 
Thank you for your help.

**Comment by mogenson** [comment]
Although it [can be done](https://colemancda.github.io/2018/03/25/Hacking-IOBluetooth), there is no public way to setup an HCI transport to the builtin Bluetooth controller on MacOS.

For Bumble on MacOS, the recommendation is to use an external Bluetooth controller over one of the [supported transports](https://google.github.io/bumble/transports/index.html).

If you're just interested in a Python wrapper over the MacOS CoreBluetooth stack, you could take a look at [bleak](https://github.com/hbldh/bleak).

**Comment by uael** [comment]
You may need to:
```
# you can see loaded classes with sudo kextstat
sudo kextunload -b com.apple.iokit.CSRBluetoothHostControllerUSBTransport
``` 
then should be able to use it over USB

**Comment by yakerm** [comment]
Thank you for your feedback. However, I'm using a USB Dongle (TP-LINK UB500). When I try to run on Macbook pro MacOS Apple M1 the example code "run_scanner.py". I have these logs attached, and nothing more happens. 

[bumble_log.zip](https://github.com/google/bumble/files/10228647/bumble_log.zip)


The same example, running on Linux, display all BLE devices found around me.

**Comment by barbibulle** [comment]
@yakerm just be sure, did you configure your mac to not attach the dongle to the macOS Bluetooth stack (see https://google.github.io/bumble/platforms/macos.html). I assume so, but always better to check.

One reason why you may be getting a different result on the mac than on Linux is that some dongles, like the TP-LINK dongle use a Realtek chipset that requires loading a firmware image at init time in order to be fully functional. Until the FW image is loaded, they look like they're working (i.e they respond to the commands) but nothing much happens. Recent versions of the Linux kernel have support for loading this FW image, so it may have been done for you automatically there. But on the mac, that doesn't happen. In fact, see the comments on issue #100 which talks about that, and maybe a solution in the near future.

**Comment by yakerm** [comment]
Hello,
I close this issue. 
I found a USB BLE dongle that works fine : 
ASUS USB-BT500
Thank you for your help.
